In [ ]:
#task1
import numpy as np

vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#task2
import numpy as np
vector=np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#task3
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#task4

import numpy as np


matrix=np.random.randint(0,1000,(3,3,3))
print(matrix)


[[[492 886 674]
  [335 936 512]
  [883 383 940]]

 [[618 962  36]
  [643 145 747]
  [121 424 214]]

 [[821 880 687]
  [785 654 598]
  [819 967 122]]]


In [11]:
#task5

import numpy as np

array=np.random.randint(0,1000,(10,10))
print("Max value in array: ", array.max())
print("Min value in array: ", array.min())

Max value in array:  992
Min value in array:  6


In [23]:
#task6

import numpy as np

vector=np.random.randint(0,1000)

mean=np.mean(vector)
print("Mean of Vector values: ", mean)

Mean of Vector values:  292.0


In [24]:
#task7

import numpy as np

arr=np.random.randint(0,100,(5,5))
normalized_value=(arr-arr.min())/(arr.max()-arr.min())

print("Original array: \n", arr)
print("\nNormalized array: \n", normalized_value)

Original array: 
 [[40 57 43 91 40]
 [73 76 33 54 75]
 [29 77 83 79 81]
 [47 71 40 27 48]
 [59 12 71 43  8]]

Normalized array: 
 [[0.38554217 0.59036145 0.42168675 1.         0.38554217]
 [0.78313253 0.81927711 0.30120482 0.55421687 0.80722892]
 [0.25301205 0.8313253  0.90361446 0.85542169 0.87951807]
 [0.46987952 0.75903614 0.38554217 0.22891566 0.48192771]
 [0.61445783 0.04819277 0.75903614 0.42168675 0.        ]]


In [2]:
#task8
import numpy as np

arr1=np.random.randint(0,100,(5,3))
arr2=np.random.randint(0,100,(3,2))
C=arr1 @ arr2

print("Multipication of 5x3 Matrix with 3x2 Matrix: \n", C)


Multipication of 5x3 Matrix with 3x2 Matrix: 
 [[ 4641 11070]
 [ 6082 10358]
 [ 3779  5078]
 [ 5944  8014]
 [ 4731  9504]]


In [3]:
#task9
import numpy as np

matrix1=np.random.randint(0,100,(3,3))
matrix2=np.random.randint(0,100,(3,3))

C=matrix1 @ matrix2 

print("Dot product of two 3x3 Matrices: \n", C)

Dot product of two 3x3 Matrices: 
 [[10389 11466  9265]
 [ 5917  5342  3981]
 [ 4944  4564  5956]]


In [4]:
#task10

import numpy as np
arr=np.random.randint(0,100,(4,4))

transpose=arr.T
print("4x4 matrix:\n", arr, "\n")
print("and its transpose:\n", transpose)


4x4 matrix:
 [[58  6 86 17]
 [90 17 71 30]
 [83 56 16 61]
 [75 95 56 24]] 

and its transpose:
 [[58 90 83 75]
 [ 6 17 56 95]
 [86 71 16 56]
 [17 30 61 24]]


In [ ]:
#task11

import numpy as np

arr=np.random.randint(0,100,(3,3))
det_arr = np.linalg.det(arr)
print("determinant: \n", det_arr)



determinant: 
 -167862.99999999985


In [7]:
#task12

import numpy as np

arr1=np.random.randint(0,100,(3,4))
arr2=np.random.randint(0,100,(4,3))

C=np.dot(arr1, arr2)
print("Dot product of two matrices: \n", C)

Dot product of two matrices: 
 [[ 4473  3656  5816]
 [ 3226  1931  3977]
 [15079 11053 16048]]


In [1]:
#task13

import numpy as np
matrix=np.random.randint(0,100,(3,3))
vector=np.random.randint(0,100,(1,3))
try:
    c=np.dot(matrix,vector)
    print(c)
except ValueError:
    print("Not possible due difference ")

Not possible due difference 


In [12]:
#task14

import numpy as np

arr1=np.random.randint(0,100,(3,3))
arr2=np.random.randint(0,100,(3,1))

x=np.linalg.solve(arr1,arr2)

print(x)

[[ 0.10118549]
 [-0.25540071]
 [ 0.83623994]]


In [13]:
#task15

import numpy as np

matrix=np.random.randint(0,100,(5,5))

sum_of_rows=matrix.sum(axis=1)
sum_of_columns=matrix.sum(axis=0)

print("5x5 matrix\n", matrix)
print(f"Sum of row: \n {sum_of_rows}")
print(f"Sof of cloums: \n{sum_of_columns}")

5x5 matrix
 [[46 32 61 45 69]
 [ 4 73 35 25 42]
 [13 29 33 48 20]
 [ 2 69 16 66 44]
 [12 41 89 45 25]]
Sum of row: 
 [253 179 143 197 212]
Sof of cloums: 
[ 77 244 234 229 200]
